In [2]:
import pandas as pd
import numpy as np

In [24]:
football_events = pd.read_csv('./data/events.csv', index_col = 'sort_order')
football_events.describe()

,time,event_type,event_type2,side,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
count,941009.000000,941009.000000,214293.000000,941009.000000,227459.000000,228498.000000,941009.000000,467067.000000,229185.000000,941009.000000,229137.000000,941009.000000
mean,49.663663,4.326575,12.233764,1.481170,5.733693,1.926555,0.025978,6.209073,1.624831,0.264332,1.281316,0.004876
std,26.488977,2.995313,0.468850,0.499646,3.326100,0.797055,0.159071,5.421736,0.740400,0.655501,0.709394,0.069655
min,0.000000,1.000000,12.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000
25%,27.000000,2.000000,12.000000,1.000000,2.000000,1.000000,0.000000,2.000000,1.000000,0.000000,1.000000,0.000000
50%,51.000000,3.000000,12.000000,1.000000,5.000000,2.000000,0.000000,3.000000,1.000000,0.000000,1.000000,0.000000
75%,73.000000,8.000000,12.000000,2.000000,9.000000,3.000000,0.000000,11.000000,2.000000,0.000000,1.000000,0.000000
max,100.000000,11.000000,15.000000,2.000000,13.000000,4.000000,1.000000,19.000000,3.000000,4.000000,4.000000,1.000000

In [25]:
football_events.head(5)

,id_odsp,id_event,time,text,event_type,event_type2,side,event_team,opponent,player,...,player_in,player_out,shot_place,shot_outcome,is_goal,location,bodypart,assist_method,situation,fast_break
sort_order,,,,,,,,,,,,,,,,,,,,,
1,UFot0hit/,UFot0hit1,2,Attempt missed. Mladen Petric (Hamburg) left f...,1,12.0,2,Hamburg SV,Borussia Dortmund,mladen petric,...,NaN,NaN,6.0,2.0,0,9.0,2.0,1,1.0,0
2,UFot0hit/,UFot0hit2,4,"Corner, Borussia Dortmund. Conceded by Dennis...",2,NaN,1,Borussia Dortmund,Hamburg SV,dennis diekmeier,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
3,UFot0hit/,UFot0hit3,4,"Corner, Borussia Dortmund. Conceded by Heiko ...",2,NaN,1,Borussia Dortmund,Hamburg SV,heiko westermann,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
4,UFot0hit/,UFot0hit4,7,Foul by Sven Bender (Borussia Dortmund).,3,NaN,1,Borussia Dortmund,Hamburg SV,sven bender,...,NaN,NaN,NaN,NaN,0,NaN,NaN,0,NaN,0
5,UFot0hit/,UFot0hit5,7,Gokhan Tore (Hamburg) wins a free kick in the ...,8,NaN,2,Hamburg SV,Borussia Dortmund,gokhan tore,...,NaN,NaN,NaN,NaN,0,2.0,NaN,0,NaN,0

In [135]:
team_1 = (football_events.event_team == 'Tottenham')
team_2 = (football_events.event_team == 'Arsenal')
team_3 = (football_events.event_team == 'Paris Saint-Germain')
football_column_drop = football_events.drop(['id_odsp','event_type','event_type2','side','location','text'], axis=1)
football_filter = football_column_drop.loc[team_1 | team_2 | team_3, : ]
football_filter.set_index('id_event') # changes a column into index
football_filter.describe()

,time,shot_place,shot_outcome,is_goal,bodypart,assist_method,situation,fast_break
count,23229.000000,6869.000000,6891.000000,23229.000000,6916.000000,23229.000000,6916.000000,23229.000000
mean,49.965819,5.531227,1.913510,0.039132,1.594708,0.339748,1.250723,0.004434
std,26.384882,3.270305,0.827367,0.193913,0.719018,0.751919,0.677417,0.066443
min,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
25%,28.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000
50%,51.000000,5.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,73.000000,8.000000,3.000000,0.000000,2.000000,0.000000,1.000000,0.000000
max,100.000000,13.000000,4.000000,1.000000,3.000000,4.000000,4.000000,1.000000

In [128]:
# chnges the name of some values.
def change_name(x) :
    if x == 'heungmin son' or x =='son heungmin' :
        x = x.replace('heungmin son', 'Son Heung-min' )
        x = x.replace('son heungmin', 'Son Heung-min' )
    return x
football_filter.player = football_filter.player.apply(lambda x: change_name(x))

In [129]:
a = football_filter.player.unique()
b = [print(player) for player in a if 'Son' in str(player)]

Son Heung-min